// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_znoR0PBHlsEE4MGcUtaQNU6n_7atdpE',
    appId: '1:1065753435665:web:42c08583c5d5def431dbb0',
    messagingSenderId: '1065753435665',
    projectId: 'students-attendance-marker',
    authDomain: 'students-attendance-marker.firebaseapp.com',
    storageBucket: 'students-attendance-marker.appspot.com',
    measurementId: 'G-F8ZR3XS22M',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnctT1F9_cKgwcRBAq_unDx5BoeMJDg8',
    appId: '1:1065753435665:ios:d305f1671af4436031dbb0',
    messagingSenderId: '1065753435665',
    projectId: 'students-attendance-marker',
    storageBucket: 'students-attendance-marker.appspot.com',
    iosClientId: '1065753435665-u9u20i767urfacsei97kianofecm3hkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhnctT1F9_cKgwcRBAq_unDx5BoeMJDg8',
    appId: '1:1065753435665:ios:d305f1671af4436031dbb0',
    messagingSenderId: '1065753435665',
    projectId: 'students-attendance-marker',
    storageBucket: 'students-attendance-marker.appspot.com',
    iosClientId: '1065753435665-u9u20i767urfacsei97kianofecm3hkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeproject',
  );
}
